version: '3'
services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
#    image: flask-python:3.6
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    links:
      - mongo



  mongo:
    image: mongo:4.4.8
    container_name: mongo
    restart: unless-stopped
#    command: mongod --auth
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongo

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
#    volumes:
#      - /var/log/nginx
    ports:
      - "80:80"
      - "443:443"


